--------------------------------------------------------
--  Fichier créé - mercredi-mars-25-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "GG"."MATERIEL" 
   (	"ID_MATERIEL" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GG.MATERIEL
SET DEFINE OFF;
Insert into GG.MATERIEL (ID_MATERIEL,NOM,ETAT) values ('7','ta','1');
--------------------------------------------------------
--  DDL for Index MATERIEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GG"."MATERIEL_PK" ON "GG"."MATERIEL" ("ID_MATERIEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MATERIEL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GG"."MATERIEL_TRG" 
BEFORE INSERT ON MATERIEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "GG"."MATERIEL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MATERIEL_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GG"."MATERIEL_TRG1" 
BEFORE INSERT ON MATERIEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_MATERIEL IS NULL THEN
      SELECT MATERIEL_SEQ1.NEXTVAL INTO :NEW.ID_MATERIEL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "GG"."MATERIEL_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "GG"."MATERIEL" ADD CONSTRAINT "MATERIEL_PK" PRIMARY KEY ("ID_MATERIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GG"."MATERIEL" MODIFY ("ID_MATERIEL" NOT NULL ENABLE);
